version: "3"

services:
  sonarqube:
    image: sonarqube:8.9.8-community
    depends_on:
    - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_FORCEAUTHENTICATION: false
    volumes:
    - type: bind
      source: ./target/sonar-test-maintainability-plugin-0.1.1-SNAPSHOT.jar
      target: /opt/sonarqube/extensions/plugins/sonar-test-maintainability-plugin.jar
    ports:
    - "9000:9000"
  sonarqube-db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
    - "5432:5432"